-- Active: 1707187512729@@127.0.0.1@3306


CREATE TABLE users (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  nickname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE posts (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  creator_id TEXT NOT NULL,
  content TEXT NOT NULL,
  votes_count INTEGER NOT NULL,
  comments_count INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES users (id)
			ON UPDATE CASCADE
			ON DELETE CASCADE
); 